import { pickLine, type VoiceLineKind } from '@/speech/voiceLines';

/**
 * Per-kind rate limit window. Different characters (monkey vs mole) can
 * speak in close succession — only same-kind lines are throttled. Audio files
 * play to completion (no clipping like SpeechSynthesis had).
 */
const MIN_INTERVAL_MS = 800;

export type { VoiceLineKind };

export interface VoiceEngine {
  speak(kind: VoiceLineKind): void;
  cancel(): void;
  setEnabled(enabled: boolean): void;
  isSupported(): boolean;
}

/**
 * Manifest shape — generated by scripts/generate-voice-pack.mjs.
 * Each kind maps to an array of { file, text } entries.
 */
interface ManifestLine {
  file: string;
  text: string;
}
type Manifest = Record<VoiceLineKind, ManifestLine[]>;

class FileSpeechEngineImpl implements VoiceEngine {
  private enabled = true;
  private manifest: Manifest | null = null;
  /** Pool of HTMLAudioElements per (kind, index) — reused to avoid GC churn. */
  private pool: Partial<Record<VoiceLineKind, HTMLAudioElement[]>> = {};
  /** Currently-playing audio per kind — used by cancel() to pause cleanly. */
  private current: Partial<Record<VoiceLineKind, HTMLAudioElement>> = {};
  private lastSpeakAtByKind: Partial<Record<VoiceLineKind, number>> = {};
  private loadPromise: Promise<void> | null = null;

  /**
   * Load manifest + preload all audio elements. Idempotent — safe to call
   * multiple times; subsequent calls return the cached promise.
   */
  load(manifestUrl = '/voice/manifest.json'): Promise<void> {
    if (this.loadPromise) return this.loadPromise;
    this.loadPromise = (async () => {
      try {
        const res = await fetch(manifestUrl);
        if (!res.ok) throw new Error(`manifest fetch ${res.status}`);
        const data = await res.json();
        this.manifest = data.lines as Manifest;
        // Preload every audio file
        const all: Promise<void>[] = [];
        for (const kind of Object.keys(this.manifest) as VoiceLineKind[]) {
          this.pool[kind] = [];
          for (let i = 0; i < this.manifest[kind].length; i++) {
            const audio = this.createAudio(this.manifest[kind][i].file);
            this.pool[kind]!.push(audio);
            all.push(this.preloadAudio(audio));
          }
        }
        await Promise.all(all);
      } catch (err) {
        console.warn('[speechEngine] load failed, voice will be silent:', err);
      }
    })();
    return this.loadPromise;
  }

  private createAudio(src: string): HTMLAudioElement {
    const a = new Audio(src);
    a.preload = 'auto';
    return a;
  }

  private preloadAudio(audio: HTMLAudioElement): Promise<void> {
    return new Promise<void>((resolve) => {
      // resolve() unconditionally — even on error, don't block the engine.
      const done = () => resolve();
      audio.addEventListener('canplaythrough', done, { once: true });
      audio.addEventListener('error', done, { once: true });
      // Force load
      audio.load();
      // Some browsers / test mocks never fire canplaythrough. Resolve after
      // a short fallback so the engine doesn't hang forever waiting.
      setTimeout(done, 50);
    });
  }

  speak(kind: VoiceLineKind): void {
    if (!this.enabled) return;
    if (!this.manifest || !this.pool[kind]) return;  // not loaded yet → silent

    const now = performance.now();
    const last = this.lastSpeakAtByKind[kind] ?? 0;
    if (last > 0 && now - last < MIN_INTERVAL_MS) return;
    this.lastSpeakAtByKind[kind] = now;

    const audios = this.pool[kind]!;
    const idx = Math.floor(Math.random() * audios.length);
    const audio = audios[idx];

    // Clone (or reuse with reset) so rapid same-kind plays don't fight
    // — each play gets its own playback instance.
    const playback = audio.cloneNode(true) as HTMLAudioElement;
    playback.volume = 0.85;
    playback.play().catch(() => {
      // Autoplay rejected — browser needs user gesture first
      // (game.ts already resumes AudioContext on first click)
    });
    this.current[kind] = playback;
  }

  cancel(): void {
    for (const audio of Object.values(this.current)) {
      try { audio?.pause(); } catch {}
    }
    this.current = {};
  }

  setEnabled(enabled: boolean): void {
    this.enabled = enabled;
    if (!enabled) this.cancel();
  }

  isSupported(): boolean {
    return typeof window !== 'undefined' && typeof Audio !== 'undefined';
  }
}

export const voice: VoiceEngine = new FileSpeechEngineImpl();

// Eagerly load manifest on module init so audio is ready when first speak() fires.
// (speak() is a no-op until load() resolves, so this is safe even on slow networks.)
if (typeof window !== 'undefined') {
  voice.load();
}